### ISSUE TITLE
CSS 考察 🥳

### ISSUE THREAD

**Issue by weikee94** [weikee94/weinotes#6]
**前言**

這裏畫三個重點給大家怎麼寫好的`html`和`css`。

- responsive design
```
- fluid layouts
- media queries
- responsive images
- correct units
- desktop first approach vs mobile first approach
```

- maintainable and scalable code
```
- clean
- easy to understand
- growth
- reusable
- how to organize file
- how to name classes
- how to structure html
```

- web performance
```
- less http requests
- less code
- compress code
- use a css preprocessor
- less images
- compress images
```

**CSS 是怎麼load的呢？🧐**
<img width="1317" alt="Screenshot 2020-02-24 at 9 27 47 PM" src="https://user-images.githubusercontent.com/13563834/75156207-92306e80-574c-11ea-95f7-f084c05107de.png">

> cascade 就是一個解決不同`css`規則衝突的過程
> process final css values 就好比像是把你所設定的%裝換成對應的值✌🏻

**CSS規則**
<img width="686" alt="Screenshot 2020-02-24 at 9 42 21 PM" src="https://user-images.githubusercontent.com/13563834/75157201-9493c800-574e-11ea-9349-1054318f6945.png">

接下來大家要記得以下的順序：

> importance > specificity > source order

```
importance

1.  User !important declarations； example: 這個是user自己調整的字體大小
2. Author !important declarations；example: 這個是developer設定的字體大小
3. Author declarations
4. User declarations
5. Default browser declarations

```

```
specificity

1. inline styles
2. id
3. classes, pseudo-classes, attribute
4. elements, pseudo-elements

```

這裏教大家怎麼看`specificity`的值：
```css
.button {
  color: red;
} 
// （0，0，1，0）

nav#nav div.pull-right .button {
  color: green;
} 
// （0，1，2，2）這個會是四個中最大的值從左邊一直向右，值最大就apply那個

a {
  color: blue;
}
// （0，0，0，1）

#nav a.button:hover {
  color: yellow;
}
// （0，1，2，1）

```

```
source order

1. the last declaration in the code will override all other declarations if 
they all have same importance and same specificity
2. but rely on order when using 3rd-party stylesheets, always put 
author stylesheets last so that urs one can overwrite or configure 3rd-party 
```
