### ISSUE TITLE
FE REV 👻

### ISSUE THREAD

**Issue by weikee94** [weikee94/weinotes#62]
```js
function* gen() {
  yield 1;
  yield 2;
}
// by calling generator function will return Generator object
const genValue = gen();
console.log(genValue.next().value); // 1
console.log(genValue.next().value); // 2
```

**Comment by weikee94** [comment]
```js
let arr = [4, 2, 1, -2];
console.log(Math.max(arr)); // NAN
console.log(Math.max(4, 2, 1, -2)); // 4
console.log(Math.max.apply(null, arr)); // 4
console.log(Math.max.call(null, arr[0], arr[1], arr[2], arr[3])); // 4
```

**Comment by weikee94** [comment]
**请写一个表格以及对应的 CSS，使表格奇数行为白色背景，偶数行为灰色背景，鼠标移 上去时为黄色背景。**
```html

<table>
  <tr>
    <td>1</td>
  </tr>
  <tr>
    <td>2</td>
  </tr>
  <tr>
    <td>3</td>
  </tr>
  <tr>
    <td>4</td>
  </tr>
</table>
```

```css

table tr:nth-child(odd) {
  background-color: white;
}

table tr:nth-child(even) {
  background-color: grey;
}

table tr:hover {
  background-color: yellow;
}
```
